project:
  type: website
  output-dir: docs
# ~ additional metadata excluded for brevity ~


website:
  title: "Sophie Pardehpoosh"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - favorite_books.qmd
      - href: resume.pdf # open browser based pdf viewer of resume when click "Resume" tab
        text: Resume
        target: _blank # opens link in new tab
  page-footer: 
    background: light
    left: copyright 2026, Sophie Pardehpoosh
    right: This website is built with [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/samanthacsik/samanthacsik.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}
      

format:
  html:
    theme: 
      - lux
      - styles.scss
    toc: true
    page-layout: full

  


