project:
  type: website
  output-dir: docs
# ~ additional metadata excluded for brevity ~


website:
  title: "Sophie Pardehpoosh"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - favorite_books.qmd
      - href: resume.pdf # open browser based pdf viewer of resume when click "Resume" tab
        text: Resume
        target: _blank # opens link in new tab
      

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    page-layout: full

  


